customCommands:
  - key: 'C'
    prompts:
      - type: 'menu'
        title: 'What kind of commit is it?'
        options:
          - name: 'featâœ¨: å¼•å…¥æ–°åŠŸèƒ½'
            description: 'å¼•å…¥æ–°åŠŸèƒ½'
            value: 'featâœ¨: '
          - name: 'fixğŸ›: ä¿®å¤bug'
            description: 'ä¿®å¤bug'
            value: 'fixğŸ›: '
      - type: 'input'
        title: 'What is the commit message'
        initialValue: ''
    command: "git flow {{index .PromptResponses 0}} start {{index .PromptResponses 1}}"
    command: 'git commit -m "{{index .PromptResponses 0}}{{index .PromptResponses 1}}"'
    context: 'commits'
    loadingText: 'add commit'